# DataFrame과 리스트, 딕셔너리, ndarray 상호 변환

## 1. 1차원 데이터를 DataFrame으로 변환

In [1]:
import warnings
warnings.filterwarnings(action='ignore')
import pandas as pd
import numpy as np

In [2]:
# 1차원 리스트 생성
list1 = [1, 2, 3]
print(type(list1), list1)

<class 'list'> [1, 2, 3]


In [17]:
# ndArray로 변환
col_name1 = [""]
col_names = ["","",""]
array1 = np.array(list1)
print(type(array1), array1)

<class 'numpy.ndarray'> [1 2 3]


In [13]:
# list1, array1를 DataFrame으로 생성(변환)
df1_1 = pd.DataFrame(list1, columns=col_name1, index=['a', 'b', 'c'])
df1_2 = pd.DataFrame(array1, columns=col_name1)
print(df1_1)
print('*' * 30)
print(df1_2)

    
a  1
b  2
c  3
******************************
    
0  1
1  2
2  3


## 2. 2차원 데이터를 DataFrame으로 변환

In [10]:
# 2차원 리스트 생성
list2 = [[1, 2, 3],
         [4, 5, 6]]
list2         

[[1, 2, 3], [4, 5, 6]]

In [11]:
#list2를 ndarray로 변환
array2 = np.array(list2)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
#list2, array2를 DataFrame으로 변환
df2_1 = pd.DataFrame(list2, columns=col_names)
df2_2 = pd.DataFrame(array2, columns=col_names)
print(df2_1)
print('-'*30)
print(df2_2)

          
0  1  2  3
1  4  5  6
------------------------------
          
0  1  2  3
1  4  5  6


## 3. 딕셔너리를 DataFrame으로 변환

In [26]:
dict1 = {
    "col1": [4, 3, 3],
    "col2": [2, 5, 6],
    "col3": [3, 5, 3]
}
dict1

{'col1': [4, 3, 3], 'col2': [2, 5, 6], 'col3': [3, 5, 3]}

In [27]:
df_dict1 = pd.DataFrame(dict1)
print(df_dict1)

   col1  col2  col3
0     4     2     3
1     3     5     5
2     3     6     3


## 4. DataFrame을 ndarray, list, dictionary로 변환

In [31]:
# df_dict1 데이터프레임을 ndarray로 변환
array3 = df_dict1.values
print(type(array3), '\n', array3)

<class 'numpy.ndarray'> 
 [[4 2 3]
 [3 5 5]
 [3 6 3]]


In [29]:
# df_dict1 데이터프레임을 list로 변환, DataRame.values > Numpy.tolist() > list
list3 = df_dict1.values.tolist()
print(type(list3), '\n', list3)

<class 'list'> 
 [[4, 2, 3], [3, 5, 5], [3, 6, 3]]


In [30]:
#df_dict1 데이터프레임을 dictionary로 변환
dict3 = df_dict1.to_dict()
print(type(dict3), '\n', dict3)

<class 'dict'> 
 {'col1': {0: 4, 1: 3, 2: 3}, 'col2': {0: 2, 1: 5, 2: 6}, 'col3': {0: 3, 1: 5, 2: 3}}


## 5. shape 속성 정리
- python List: ❌ AttributeError
- python Dictionary: ❌ AttributeError
- Numpy ndarray: 사용 가능
- Pandas DataFrame: 사용 가능
- Pandas Series: 사용 가능

In [ ]:
# list 생성
print(type(list1), list1)
print(f"shape : {list1.shape}") # ❌ AttributeError: 'list' object had no attribute 'shape'

In [ ]:
# dictionary 생성
print(type(dict1), dict1)
print(f"shape : {dict1.shape}") # ❌ AttributeError: 'dict' object had no attribute 'shape'

In [34]:
# array
print(type(array1), array1)
print(f"shape : {array1.shape}")

<class 'numpy.ndarray'> [1 2 3]
shape : (3,)


## 6. DataFrame 컬럼 데이터 생성 및 수집

### 타이타닉(Titanic) 데이터 셋 로드

In [35]:
titanic_df = pd.read_csv('data/titanic/train.csv')
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
